name: JUnit Tests

on:
  pull_request:
    branches: [ master ] # Replace with your main branch

permissions:
  contents: read
  actions: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Run tests
        run: mvn test

      - name: Upload Surefire reports (only for same-repo PRs)
        if: github.event.pull_request.head.repo.full_name == github.repository
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports/

      - name: Report tests
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: JUnit Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: false
