name: JUnit Tests

on:
  pull_request:
    branches: [ master ] # Replace with your main branch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Run tests
        run: mvn test # Or ./gradlew test

      - name: Report tests
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: JUnit Tests
          path: target/surefire-reports/*.xml # Or build/test-results/test/*.xml
          reporter: java-junit
          fail-on-error: false
