name: JUnit Tests

on:
  pull_request_target:
    branches: [ master ] # Replace with your default branch
  workflow_dispatch:     # Allow manual triggering from the GitHub UI

permissions:
  contents: read
  actions: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # ⚠️ SECURITY: Do NOT checkout PR code directly unless it's safe to do so.
      - name: Checkout code from base (safe)
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.ref }}

      # ✅ Only do the following if you trust the PR or validate it first
      # - name: Checkout PR code (risky if untrusted)
      #   uses: actions/checkout@v3
      #   with:
      #     ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Run tests
        run: mvn test

      - name: Upload Surefire reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports/

      - name: Report tests
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: JUnit Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: false
